[book]
authors = ["clearloop"]
language = "en"
multilingual = false
src = "src"
title = "the-elvis-blog"

[build]
build-dir = "docs"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/elvisjs/elvis"